# -*- coding: utf-8 -*-
"""Random Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12cvVQf7XluKHd06cgOSv2miRfO5oZHuq
"""

# Random numbers Matrix multlipication

import random   # importing an inbuilt function to generate random numbers
import numpy as n # numpy helps to generate a random number between 0-1

r=3 # number of rows
c=3 # number of colums


m1=[[0 for _ in range(r)]for _ in range(c)]

for i in range(3):
  for j in range(3):
    a=random.randint(-999,999)
    m1[i][j]=a
  
print("\nmatrix m1 =")
for x in m1:
  print(x)
print("\n\n")


m2=[[0 for _ in range(r)]for _ in range(c)]

for i in range(3):
  for j in range(3):
    b=random.randint(-999,999)
    m2[i][j]=b

print("\nmatrix m2 =")
for x in m2:
  print(x)
print("\n\n")


ma=[[0 for _ in range(r)]for _ in range(c)]

# multiply
ma = n.dot(m1,m2)

print("\n Multiplied matrix ma =")
print(ma)