# -*- coding: utf-8 -*-
"""A3_Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13OQG4mDn-ZhrE0FeSYU8sEyj0czu892T
"""

import math as m

def Get_Rig(T,E0,Z): 

    RJ = ((m.sqrt( (T+E0)**2 - E0**2)) / (3E8 * 1.6E-19 * Z)) # Rigidity
    EL = ((((1.6E-19*Z)**2 *(m.sqrt(1-(1/((T/E0)+1)**2)))**3*((T/E0)+1)**4)/(3*8.85418782E-12*(561.6/(2*m.pi))))/1.6E-19) # Energy Loss
    Theta = (180) / (((T/E0)+1) * m.pi) # 

    print(f'Rigidity\t= {RJ:.3f} Tm \nEnergy loss\t= {EL} eV \nTheta\t\t= {Theta:.4f}°')
    print("\n----------------------------------------------")

print("1-")
Get_Rig(7.24E-9,3.552E-8,28)

print("2-")
Get_Rig(1.29E-8, 3.272E-8, 77)

print("3-")
Get_Rig(1.6E-9, 8.186E-14, 1)