# -*- coding: utf-8 -*-
"""A3_Q9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKpsqfIJwOHRHklxmTMQbU9p2Vns6zBv
"""

# Question 9

import numpy as n
import matplotlib.pyplot as pt

a = n.loadtxt("data.txt", dtype=float) # Saving the data in an array 

m = n.max(a)      # Finding the maximum value isn the array
im = n.argmax(a)  # Index of the maximum value in the array 

pt.scatter(im,m,color='red') # Highest point
pt.plot(a,'blue') # Plot Graph

pt.title('Q9 Graph') # Title for the graph
pt.grid(color='black') # For the grid
pt.show() # Display