# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQN7pzVUJzd2yUhGAsqKCIImgDL841A2
"""

# Use init and start
"""
# AJ's code 

Z = input("Enter the number of protons (charge):")
print(f"Z={Z}")
A = input("Enter the atomic mass (in u):")

class NeutronFinder:
    def __init__(self, Z, A):
        self.Z = Z
        self.A = A

    def complicatedCalculator(self):
        N = int(self.A) - int(self.Z)
        print("The number of neutrons is %d." % N)
        
Example = NeutronFinder(Z,A)
Example.complicatedCalculator()

"""
# Note: This assignment is absolutely stupid as this is basic sunbtraction and it is done with inheritance and classes, there is no point in this assignment asssssssssss

# My code 
"""
class Neu:
    
    def __init__(self):
        self.A = int(input('Input total number of Nucleons (A) = '))
        self.Z = int(input('Number of protons (Z) = '))
        self.N = self.A - self.Z
    
    def Print(self):
      print('Number of Neutrons (N) = ',self.N)

A = Neu()
A.Print()
"""
# Test 1
"""
#x=int(input('total number of nucleons = ')) # add int or else it won't recognise the comand
#x=3
#print("x=",x)
#y=int(input('Number of protons (Z) = '))
#y=1
#print('y=',y)

class test:
    
    def __init__(self, x, y, n):
        self.x = x
        #self.x = int(input('Innput total number of Nucleons (A) = '))
        self.y = y
        #self.y = int(input('Number of protons (Z) = '))
        self.n = self.x - self.y
    
    def Print(self):
      print('Number of Neutrons (N) = ',self.n)

a= x-y

t1=test(9,8,a)
t1.Print()



#print('Number of Neutrons = ',a)
"""
# Variation 2 **************************************************** works
"""
class Neutrons:
    
    def __init__(self, x, y):
        self.x = x
        
        self.y = y
        
        self.n = self.x - self.y
    
    def Print(self):
      print('Number of Neutrons (N) = ',self.n)


A=Neutrons(9,8) # mention the number of nucleons and protons (A,Z)
A.Print()
"""
# Variation 3 ******************************************************* Works
"""
#x=int(input('total number of nucleons = ')) 

#print("x=",x)
#y=int(input('Number of protons (Z) = '))

#print('y=',y)

class test:
    
    def __init__(self, x, y):
        self.x = x
        
        self.y = y
        
        self.n = self.x - self.y
    
    def Print(self):
      print('Number of Neutrons (N) = ',self.n)

t1=test(x=int(input('total number of nucleons = ')) ,y=int(input('Number of protons (Z) = ')))
t1.Print()
"""

class Neu:
    
    def __init__(self):
        self.A = int(input('Input total number of Nucleons (A) = '))
        self.Z = int(input('Number of protons (Z) = '))
        self.N = self.A - self.Z
    
    def Print(self):
      print('\nNumber of Neutrons (N) = ',self.N)

A = Neu()
A.Print()

class test:
    
    def __init__(self, x, y):
        self.x = x
        
        self.y = y
        
        self.n = self.x - self.y
    
    def Print(self):
      print('\n\nNeutrons = ',self.n)

t1=test(x=int(input('Mass number = ')) ,y=int(input('Number of protons = ')))
t1.Print()